version: '3.7'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    # '/start' is the shell script used to run the service
    command: /start-fastapi.sh
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - rabbit
    networks:
      - external_bridge_network

  rabbit:
    image: rabbitmq:latest
    networks:
      - external_bridge_network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: /start-celeryworker.sh
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - rabbit
    networks:
      - external_bridge_network

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: /start-consumer.sh
    volumes:
      - .:/app
    networks:
      - external_bridge_network

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: /start-flower.sh
    volumes:
      - .:/app
    env_file:
      - .env.dev
    ports:
      - 5557:5555
    depends_on:
      - rabbit
    networks:
      - external_bridge_network

networks:
  external_bridge_network:
    external:
      name: bridge_network_inno_automate